#!/bin/bash

set -e

output_dir=$1
glsl_path=$2

glsl_filename=$(basename -- "$glsl_path")
shader_output_dir=$output_dir/$glsl_filename

mkdir -p $shader_output_dir

SATEN_IP=saten
SATEN_DEVICE_ID=7956
SATEN_SM_VERSION=SM75

KIYAMA_IP=kiyama
KIYAMA_DEVICE_ID=9634
KIYAMA_SM_VERSION=SM86

DOLLY_IP=dolly
DOLLY_DEVICE_ID_SM89=10370
DOLLY_DEVICE_ID_SM86=9350
DOLLY_DEVICE_ID_SM75=7944
DOLLY_DEVICE_ID=$DOLLY_DEVICE_ID_SM75
DOLLY_SM_VERSION=SM75


IP=$SATEN_IP
DEVICE_ID=$SATEN_DEVICE_ID
SM_VERSION=$SATEN_SM_VERSION

#IP=$KIYAMA_IP
#DEVICE_ID=$KIYAMA_DEVICE_ID
#SM_VERSION=$KIYAMA_SM_VERSION

IP=$DOLLY_IP
DEVICE_ID=$DOLLY_DEVICE_ID
SM_VERSION=$DOLLY_SM_VERSION

python3 scripts/compile_shader.py --debug --host $IP --device-id $DEVICE_ID $shader_output_dir $glsl_path
nvdisasm -hex -b $SM_VERSION $shader_output_dir/shader_data.bin | tee $shader_output_dir/shader_data.asm
hexdump -C $shader_output_dir/shader_header.bin > $shader_output_dir/shader_header.hex
hexdump -C $shader_output_dir/mesh_shader_header_gs.bin > $shader_output_dir/mesh_shader_header_gs.hex
hexdump -C $shader_output_dir/shader_zstd_dec.bin > $shader_output_dir/shader_zstd_dec.hex

if [ "$TERM_PROGRAM" = "vscode" ]; then
if [ "$CHROME_DESKTOP" = "codium.desktop" ]; then
  codium $shader_output_dir/shader_data.asm
else
  code $shader_output_dir/shader_data.asm
fi
fi
