#!/bin/bash

set -e

output_dir=$1
spv_path=$2

spv_filename=$(basename -- "$spv_path")
shader_output_dir=$output_dir/$spv_filename

mkdir -p $shader_output_dir

SATEN_IP=192.168.1.24
SATEN_VENDOR_ID=4318
SATEN_DEVICE_ID=7956
SATEN_SM_VERSION=SM75

KIYAMA_IP=192.168.1.45
KIYAMA_VENDOR_ID=4318
KIYAMA_DEVICE_ID=9634
KIYAMA_SM_VERSION=SM86


IP=$SATEN_IP
VENDOR_ID=$SATEN_VENDOR_ID
DEVICE_ID=$SATEN_DEVICE_ID
SM_VERSION=$SATEN_SM_VERSION

spirv-as --target-env vulkan1.3 $spv_path -o $shader_output_dir/output.spv
cargo run --bin nvshaderdump -- remote --hostname $IP --port 9999 --vendor-id $VENDOR_ID --device-id $DEVICE_ID "$shader_output_dir/output.spv" --output-directory "$shader_output_dir"
nvdisasm -hex -b $SM_VERSION $shader_output_dir/shader_data.bin | tee $shader_output_dir/shader_data.asm
hexdump -C $shader_output_dir/shader_header.bin > $shader_output_dir/shader_header.hex
hexdump -C $shader_output_dir/shader_zstd_dec.bin > $shader_output_dir/shader_zstd_dec.hex
