#!/bin/bash

set -e

output_dir=$1
glsl_path=$2

glsl_filename=$(basename -- "$glsl_path")
shader_output_dir=$output_dir/$glsl_filename

compiler_extensions=$(python3 $PWD/scripts/extract_compile_args.py $glsl_path compiler_extensions)
compiler_shader_flags=$(python3 $PWD/scripts/extract_compile_args.py $glsl_path compiler_shader_flags)

mkdir -p $shader_output_dir

SATEN_IP=saten
SATEN_VENDOR_ID=4318
SATEN_DEVICE_ID=7956
SATEN_SM_VERSION=SM75

KIYAMA_IP=kiyama
KIYAMA_VENDOR_ID=4318
KIYAMA_DEVICE_ID=9634
KIYAMA_SM_VERSION=SM86

DOLLY_IP=dolly
DOLLY_VENDOR_ID=4318
DOLLY_DEVICE_ID=10370
DOLLY_SM_VERSION=SM89


IP=$SATEN_IP
VENDOR_ID=$SATEN_VENDOR_ID
DEVICE_ID=$SATEN_DEVICE_ID
SM_VERSION=$SATEN_SM_VERSION

#IP=$KIYAMA_IP
#VENDOR_ID=$KIYAMA_VENDOR_ID
#DEVICE_ID=$KIYAMA_DEVICE_ID
#SM_VERSION=$KIYAMA_SM_VERSION

#IP=$DOLLY_IP
#VENDOR_ID=$DOLLY_VENDOR_ID
#DEVICE_ID=$DOLLY_DEVICE_ID
#SM_VERSION=$DOLLY_SM_VERSION

glslangValidator -g0 --target-env vulkan1.3 $glsl_path -o $shader_output_dir/output.spv
cargo run --bin nvshaderdump -- remote --hostname $IP \
                                       --port 9999 \
                                       --vendor-id $VENDOR_ID \
                                       --device-id $DEVICE_ID \
                                       "$shader_output_dir/output.spv" \
                                       --output-directory "$shader_output_dir" \
                                       --extensions "$compiler_extensions" \
                                       --shader-flags "$compiler_shader_flags"
nvdisasm -hex -b $SM_VERSION $shader_output_dir/shader_data.bin | tee $shader_output_dir/shader_data.asm
hexdump -C $shader_output_dir/shader_header.bin > $shader_output_dir/shader_header.hex
hexdump -C $shader_output_dir/mesh_shader_header_gs.bin > $shader_output_dir/mesh_shader_header_gs.hex
hexdump -C $shader_output_dir/shader_zstd_dec.bin > $shader_output_dir/shader_zstd_dec.hex

if [ "$TERM_PROGRAM" = "vscode" ]; then
  code $shader_output_dir/shader_data.asm
  true
fi
