[package]
name = "usami-binaries"

version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
ash.workspace = true
usami.workspace = true
image.workspace = true
